name: Steel Security
version: 0.1a
description: The most EPIC protection plugin on the market :)featuring fully automated hack/grief/spam protection!
main: net.othercraft.steelsecurity.Main
load: POSTWORLD
authors: [Mike111177, CorrieKay] 
website: http://othercraft.net
database: false #I assume we will need one later
commands:
  sts:
     description: Base command for Steel Security.
     usage: /sts
permissions:
  steelsecurity.*:
    description: Gives access to all Steel Security commands and actions
    children:
     steelsecurity.command.*: true
     steelsecurity.antispam.*: true