name: SteelSecurity
version: 0.9a
main: net.othercraft.steelsecurity.Main
authors: [Mike111177, CorrieKay, r0306]
website: http://othercraft.net
commands:
  sts:
     description: Base command for Steel Security.
     usage: /sts
permissions:
  steelsecurity.*:
     description: Gives all benificial Steel Security permissions.
     children: 
        steelsecurity.commands.*: true
        steelsecurity.bypass.*: true
        steelsecurity.commands.vanish.cansee: true
  steelsecurity.bypass.*: 
     description: Gives permission to bypass all of Steel securitys checks.
     default: op
     children: 
        steelsecurity.bypass.anticaps: true
        steelsecurity.bypass.antiflood: true
        steelsecurity.bypass.loginlimiter: true
        steelsecurity.bypass.censor: true
        steelsecurity.bypass.blockblackist: true
  steelsecurity.commands.*: 
     description: Gives access to all Steel Security commands.
     default: op
     children: 
        steelsecurity.commands.sts: true
        steelsecurity.commands.help: true
        steelsecurity.commands.checkperm: true
        steelsecurity.commands.spectate: true
        steelsecurity.commands.listop: true
        steelsecurity.commands.checkgm: true
        steelsecurity.commands.reload: true
        steelsecurity.commands.vanish: true
  steelsecurity.commands.vanish.cansee:
     description: Gives access to see vanished people.
     default: op
        