name: Steel Security
version: 0.2.0.1a
main: net.othercraft.steelsecurity.Main
authors: [Mike111177, CorrieKay]
website: http://othercraft.net
commands:
  sts:
     description: Base command for Steel Security.
     usage: /sts